### ISSUE TITLE
uninitialized constant ActiveSupport::Dependencies::Mutex

### ISSUE THREAD

**Issue by agenteo** [iain/metrical#2]
I've installed metrical (0.0.4)

$ ruby script/about 
About your application's environment
Ruby version              1.8.7 (i686-darwin10.3.0)
RubyGems version          1.6.2
Rack version              1.1
Rails version             2.3.8

OSX 10.6.6

when I run metrical I get [1]

I had to add:
require 'thread'
to the rails app to solve a known issue between rails 2.3.8 and ruby gems 1.6

[1]
/Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/gems/rake-0.8.7/lib/rake.rb:2503:in `const_missing': uninitialized constant ActiveSupport::Dependencies::Mutex (NameError)
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:55
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/gems/activesupport-2.3.8/lib/active_support.rb:57
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/gems/activesupport-2.3.8/lib/activesupport.rb:1
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/gems/metric_fu-2.0.1/lib/metric_fu.rb:7
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in`gem_original_require'
    from /Users/enrico/.rvm/rubies/ruby-1.8.7-p249/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/gems/metrical-0.0.4/bin/metrical:4
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/bin/metrical:19:in`load'
    from /Users/enrico/.rvm/gems/ruby-1.8.7-p249@reachout/bin/metrical:19

**Comment by agenteo** [comment]
hey I sort of solved it by myself, I just add to add
require 'thread'
to the script:
.rvm/gems/ruby-1.8.7-p249@reachout/bin/metrical
